### ISSUE TITLE
Segfaults on successive connections

### ISSUE THREAD

**Issue by wagafo** [theinvisible/openfortigui#28]
openfortiGUI 0.4.2
Ubuntu 18.04

If I start openfortigui I'm able to connect to my VPN the first time. If I disconnect and try to connect again. openfortgui crashes. After the crash, without closing openfortigui, I'm able to connect agin.

This is what I see in my syslog:
[74755.498040] QThread[30309]: segfault at 1533c0a ip 00007f0e589af5a1 sp 00007f0e52b15148 error 4 in libc-2.27.so[7f0e58821000+1e7000]

If it helps, my Internet connection has a big latency (700 ms or so) because I have to connect from a satellite dish, but the speed is OK, around 15 Mbits.

**Comment by theinvisible** [comment]
Hi,

please try again with the latest version of OpenFortiGUI 0.6.0. Also i didnt have tested now for Ubuntu 18.04. I will test for 18.04 when it is officially released on April 26. 

High latency should not be a problem because we also use it over slow mobile connections. But as said, please try version 0.6.0 first.

Regards
Rene

**Comment by wagafo** [comment]
I've installed 0.6.0 and still seeing the same issue. First connection after stating OK, disconnect, try connection again and OpenFortiGui crashes. The message in syslog is similar:
[109536.686582] QThread[9172]: segfault at 3533c0a ip 00007fd25b86c5a1 sp 00007fd2549050b8 error 4 in libc-2.27.so[7fd25b6de000+1e7000]

**Comment by wagafo** [comment]
This crash I'm observing only at this connection with large latency. In another connection that I'm using I have never had this crash (fiber optics speed).

**Comment by matjam** [comment]
I get the same issue on Ubuntu 17.10.

First VPN will work fine.
Shut the connection down and it appears to not restore the route table..
have to hard kill all vpn related process and restart the local connection.
Then it works again.

**Comment by matjam** [comment]
No, very low latency network.

So, since applying latest security patches to 17.10, it seems stable. glibc and some other stuff was updated.

**Comment by matjam** [comment]
Sorry the ubuntu crash reporter eats the files or something, but here's some screenshots:

![image](https://user-images.githubusercontent.com/578676/39391403-87109dee-4a57-11e8-818f-42cff84243b2.png)

![image](https://user-images.githubusercontent.com/578676/39391421-be803014-4a57-11e8-8938-a42ae19787a3.png)

![image](https://user-images.githubusercontent.com/578676/39391423-cc901f3e-4a57-11e8-854f-8d7307dbec94.png)

hope this helps.

**Comment by wagafo** [comment]
I've been trying the site where the connection crashes, and it is crashing a lot now. Almost every time I start the connection crashes the first time. This last time I tried, it has crashed already 3 times in a row and it is not able to connect.

**Comment by matjam** [comment]
So, I updated to 18.04. I didn't try openfortigui yet but will do tonight and see if I get the same issues.

If I do, I think we need a debug build, with symbols. It's crashing in vfprintf which is usually a sign of wrong printf format parameters or something like that in the function that's calling vfprintf.

**Comment by theinvisible** [comment]
Thanks for your further information.

I wasnt able to dig deeper until now but will do later on when there is more time.

If you want to help debugging, follow my instructions on the other issue to build a debug binary: https://github.com/theinvisible/openfortigui/issues/27#issuecomment-379489453

**Comment by theinvisible** [comment]
After my first (shorter) debug session i could not reproduce the crashes you mentioned here.

First i setup the latency to 700ms: tc qdisc add dev enp0s31f6 root netem delay 700ms

Then i tried connecting to serveral fortigate gateways and also reconnecting the same vpn. I will enhance the test later on, also with gdb.

Maybe you can also test on your faster links if the problem persits. Just execute the command above to raise the network delay, thanks.

**Comment by wagafo** [comment]
Thanks theinvisible. I will try to reproduce the crash and debug it this Sunday, at the site where I can reproduce the crash consistently.

**Comment by wagafo** [comment]
I kept trying to get the crash starting openfortigui from the command line, but I was never able to reproduce it. Instead starting it from gui or the app indicator I get the crash consistently as explained in the report, that is it crashes the first time and then it starts correctly. 

This is all on the high latency connection (700 ms in average). I never got the crash in a low latency connection.

**Comment by matjam** [comment]
I don't think it has anything to do with latency. I have a low latency connection and it crashes consistently, I just can't get my debug binary to work.

@theinvisible is it possible you can build a package with debug symbols?

**Comment by theinvisible** [comment]
@matjam Have you tried to follow my short instructions to build debug binaries: https://hadler.me/linux/openfortigui/

Another question: Are you using a hostname for your VPN-server gateway or IP? I got also reports that there are issues with hostname resolving on some setups.

**Comment by matjam** [comment]
@theinvisible I tried. I'll have another try again, but the issue was that the binary I built wouldn't connect to the VPN, yet your binaries work fine.

I've also installed 0.6.1 package from https://hadler.me/linux/openfortigui/ and still have the same problem.

The issue is happening when you quit openfortigui while it is running. If you just stop the VPN and don't quit openfortigui, it does not crash. When it crashes, it does not reset the network, so you need to down/up the interface for it to recover.

**Comment by matjam** [comment]
OK, so, my debug binary won't start the VPN unlike your release build; I am able to grab the ubuntu apport analysis which has a stacktrace in it and a complete core file. As the core may have sensitive information in it, I'm not keen to hand that out, but can pass on the stack trace:

```
Stacktrace:
 #0  0x000055c4f54eb720 in vpnWorker::end (this=0x55c4f688c790) at proc/vpnworker.cpp:470
 No locals.
 #1  0x000055c4f54df00f in vpnProcess::closeProcess (this=0x7ffff4aa11d0) at proc/vpnprocess.cpp:52
         __PRETTY_FUNCTION__ = "void vpnProcess::closeProcess()"
 #2  0x000055c4f55033f9 in vpnProcess::qt_static_metacall (_o=0x7ffff4aa11d0, _c=QMetaObject::InvokeMetaMethod, _id=5, _a=0x7f76f8006160) at moc_vpnprocess.cpp:97
         _t = 0x7ffff4aa11d0
 #3  0x00007f7706748122 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #4  0x00007f7706718991 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #5  0x00007f770671b11d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #6  0x00007f77067722c3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #7  0x00007f7703a00287 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #8  0x00007f7703a004c0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #9  0x00007f7703a0054c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #10 0x00007f77067718ef in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #11 0x00007f77067169ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #12 0x00007f770671fa84 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #13 0x000055c4f54b5fb0 in main (argc=6, argv=0x7ffff4aa15e8) at main.cpp:150
```

I don't know if it's related to the crash we see on shutdown of the VPN, but the more the merrier?

**Comment by matjam** [comment]
Sorry, I should have mentioned, I'm using 18.04 now.

**Comment by theinvisible** [comment]
Hi,

there is OpenFortiGUI 0.7 out now, you can give it a try. Have you also tried openfortivpn?

Regards
Rene
